TILE_SIZE = 32

DEFAULT_HIGH_RANK = 25
DEFAULT_LOW_RANK = 5
DEFAULT_HIGH_QUALITY = 95
DEFAULT_LOW_QUALITY = 30
DEFAULT_HIGH_PCA = 0.98
DEFAULT_LOW_PCA = 0.80
DEFAULT_HIGH_K = 64
DEFAULT_LOW_K = 16
DEFAULT_HIGH_WAVELET = 80
DEFAULT_LOW_WAVELET = 20

ALGORITHM_OPTIONS = [
    'SVD', 'DCT', 'PIL', 'PCA', 'KMeans', 'Wavelet', 'Autoencoder'
]